version: '3'
services:
    php:
        build: .
        volumes:
            - .:/var/www/html
        expose:
            - 80
    mysql:
        image: mysql:8
        environment:
          - MYSQL_ALLOW_EMPTY_PASSWORD=1
        expose:
            - 3306